pages/urls.py
from django.contrib import admin
from django.urls import path

from pages import views

urlpatterns = [
    path('', views.home, name='home'),
    path('test_error', views.test_error, name='test_error'),
]

payup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("allauth.urls")),  # allauth URL-larini qo'shish
    path('', include('pages.urls'), name='home'),
    # path('contract/', include('contract.urls'), name='home'),
    path('stepform/', include('stepform.urls'), name='stepform'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stepform/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    # Contract turi yuboriladi. Mikrokredit/Mikroqarz/Sugurta
    path('step_contract/<str:credit_type>/', views.step_contract, name='step_contract'),
    path('step_customer/', views.step_customer, name='step_customer'),
    path('step_pledge/', views.step_pledge, name='step_pledge'),
    path('done/', views.done, name='done'),

    # OPERATOR
    path('operator_list/', views.operator_list, name='operator_list'),

    # MODERATOR
    path('moderator_list/', views.moderator_list, name='moderator_list'),
    path('moderator_form/<int:pk>/', views.moderator_form, name='moderator_form'),

    # DIREKTOR
    path('direktor_list/', views.direktor_list, name='direktor_list'),
    path('direktor_form/<int:pk>/', views.direktor_form, name='direktor_form'),

    # KREDITLASH LOAN
    path('loan_head_list/', views.loan_head_list, name='loan_head_list'),
    path('loan_head_form/<int:pk>/', views.loan_head_form, name='loan_head_form'),

    # MONITORING LOAN
    path('monitoring_head_list/', views.monitoring_head_list, name='monitoring_head_list'),
    path('monitoring_head_form/<int:pk>/', views.monitoring_head_form, name='monitoring_head_form'),
]

stepform/models.py
from django.contrib.auth.models import User
from django.db import models
from openpyxl.styles.builtins import percent


class ContractStep(models.Model):
    id = models.AutoField(primary_key=True)
    created_by = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    contract_number = models.CharField(max_length=500, unique=True, blank=True, null=True)
    contract_date = models.DateField(blank=True, null=True)
    credit_start_date = models.DateField(blank=True, null=True)
    credit_end_date = models.DateField(blank=True, null=True)
    credit_loan_total = models.IntegerField(blank=True, null=True)
    credit_loan_total_word_uz = models.CharField(max_length=1024, blank=True, null=True)
    credit_percent = models.IntegerField(blank=True, null=True)
    credit_percent_word_uz = models.CharField(max_length=1024, blank=True, null=True)
    credit_term = models.PositiveIntegerField(help_text="Muddat oyda", blank=True, null=True)
    credit_term_word_uz = models.CharField(max_length=1024, blank=True, null=True)
    credit_type = models.CharField(max_length=512)
    credit_graphic_type = models.CharField(max_length=512)
    insurance_premium = models.IntegerField(blank=True, null=True)
    insurance_premium_word_uz = models.CharField(max_length=512)

    def __str__(self):
        return self.contract_number

    class Meta:
        db_table = 'contract'
        managed = False


class Customer(models.Model):
    id = models.AutoField(primary_key=True)
    created_by = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    customer_passport_series = models.CharField(max_length=5, blank=True, null=True)  # Pasport seriyasi (AA, AB, AC...)
    customer_passport_number = models.CharField(max_length=10, blank=True, null=True)  # Pasport raqami
    customer_passport_pinfl = models.CharField(max_length=14, blank=True, null=True)  # PINFL (14 xonali)
    customer_birthDate = models.DateField()  # Tug‘ilgan sana
    customer_document = models.CharField(max_length=255, blank=True, null=True)  # Hujjat fayli
    customer_fullname = models.CharField(max_length=512, blank=True, null=True)  # To‘liq ism
    customer_fullname_initials = models.CharField(max_length=512, blank=True, null=True)  # Ism-sharif initsiallari
    customer_issuedBy = models.CharField(max_length=1024, blank=True, null=True)  # Kim tomonidan berilgan
    customer_startDate = models.DateField(blank=True, null=True)  # Pasport berilgan sana
    customer_endDate = models.DateField(blank=True, null=True)  # Pasport amal qilish muddati sana
    customer_address = models.TextField(blank=True, null=True)  # Mijozning manzili
    customer_phone1 = models.CharField(max_length=255, blank=True, null=True)  # Asosiy telefon raqami
    customer_phone2 = models.CharField(max_length=255, blank=True, null=True)  # Qo‘shimcha telefon
    customer_phone3 = models.CharField(max_length=255, blank=True, null=True)  # Qo‘shimcha telefon
    customer_average_monthly_income = models.IntegerField(blank=True, null=True)  # Mijozning o‘rtacha oylik daromadi
    customer_average_monthly_income_word = models.CharField(max_length=1024, blank=True,
                                                            null=True)  # Mijozning o‘rtacha oylik daromadi
    customer_average_monthly_expenses = models.IntegerField(blank=True, null=True)  # O‘rtacha oylik xarajatlari
    customer_average_monthly_expenses_word = models.CharField(max_length=1024, blank=True,
                                                              null=True)  # O‘rtacha oylik xarajatlari
    customer_position = models.CharField(max_length=1024, blank=True, null=True)  # O‘rtacha oylik xarajatlari
    customer_first_principal_payment = models.IntegerField(blank=True, null=True)  # Birinchi oy uchun toʻlov
    customer_first_principal_payment_word = models.CharField(max_length=1024, blank=True,
                                                             null=True)  # Birinchi oy uchun toʻlov

    def __str__(self):
        return self.customer_fullname

    class Meta:
        db_table = 'customer'
        managed = False


class Pledge(models.Model):
    id = models.AutoField(primary_key=True)
    created_by = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    pledge_is_owner = models.CharField(max_length=255, blank=True, null=True)  # Garovga qo‘ygan shaxs egami yoki yo‘q
    pledge_vehicle_TP_series = models.CharField(max_length=255, blank=True, null=True)  # Texnik pasport seriyasi
    pledge_vehicle_TP_number = models.CharField(max_length=255, blank=True, null=True)  # Texnik pasport raqami
    pledge_vehicle_techPassportIssueDate = models.DateField(blank=True, null=True)  # Texnik pasport berilgan sana
    pledge_vehicleColor = models.CharField(max_length=255, blank=True, null=True)  # Avtomobil rangi
    pledge_issueYear = models.PositiveIntegerField(blank=True, null=True)  # Ishlab chiqarilgan yil
    pledge_engineNumber = models.CharField(max_length=255, blank=True, null=True)  # Dvigatel raqami
    pledge_shassi = models.CharField(max_length=255, blank=True, null=True)  # Shassi raqami
    pledge_vehicleTypeStr = models.CharField(max_length=255, blank=True, null=True)  # Avtomobil turi
    pledge_bodyNumber = models.CharField(max_length=255, blank=True, null=True)  # Kuzov raqami
    pledge_govNumber = models.CharField(max_length=255, blank=True, null=True)  # Davlat raqami (YTH 01)
    pledge_modelName = models.CharField(max_length=255, blank=True, null=True)  # Avtomobil modeli
    pledge_owner = models.CharField(max_length=1024, blank=True, null=True)  # Avtomobil egasi

    pledge_loan_total = models.IntegerField(blank=True, null=True)  # Garov qiymati
    pledge_loan_total_word_uz = models.CharField(max_length=1024)  # Garov summasi so‘z bilan
    pledge_division = models.CharField(max_length=1024)

    def __str__(self):
        return f"{self.pledge_modelName} - {self.pledge_govNumber} ({self.pledge_loan_total} UZS)"

    class Meta:
        db_table = 'pledge'
        managed = False


class Organization(models.Model):
    id = models.AutoField(primary_key=True)

    title = models.CharField(max_length=255, blank=True, null=True)  # Tashkilot nomi
    address = models.CharField(max_length=255, blank=True, null=True)  # Tashkilot manzili
    account_number = models.CharField(max_length=50, blank=True, null=True)  # Hisob raqami
    mfo = models.CharField(max_length=10, blank=True, null=True)  # Bank MFO kodi
    stir = models.CharField(max_length=15, blank=True, null=True)  # Soliq identifikatsiya raqami (STIR)

    phone1 = models.CharField(max_length=20, blank=True, null=True)  # 1-telefon raqami
    phone2 = models.CharField(max_length=20, blank=True, null=True)  # 2-telefon raqami
    direktor_fullname = models.CharField(max_length=512, blank=True, null=True)  # Direktor FIO
    direktor_initials = models.CharField(max_length=512, blank=True, null=True)  # Direktor  initials
    loan_head_fullname = models.CharField(max_length=512, blank=True, null=True)  # Kreditlash FIO
    loan_head_initials = models.CharField(max_length=512, blank=True, null=True)  # Kreditlash  initials
    monitoring_head_fullname = models.CharField(max_length=512, blank=True, null=True)  # Monitoring FIO
    monitoring_head_initials = models.CharField(max_length=512, blank=True, null=True)  # Monitoring initials

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'organization'  # Jadval nomini PostgreSQLda 'organization' qilib saqlaydi
        managed = False


class Branch(models.Model):
    id = models.AutoField(primary_key=True)
    created_by = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=1024, blank=True, null=True)
    head_fullname = models.CharField(max_length=1024, blank=True, null=True)  # Markaz rahbari FIO
    head_initials_uz = models.CharField(max_length=1024, blank=True, null=True)  # Markaz rahbari initials
    state = models.BooleanField(default=True)
    position = models.CharField(max_length=1024, blank=True, null=True)  # Lavozimi

    def __str__(self):
        return f"Application {self.head_initials_uz} "

    class Meta:
        db_table = 'branch'
        managed = False


class Application(models.Model):
    id = models.AutoField(primary_key=True)
    created_by = models.IntegerField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    contract_id = models.IntegerField(blank=True, null=True)
    customer_id = models.IntegerField(blank=True, null=True)
    owner_id = models.IntegerField(blank=True, null=True)
    pledge_id = models.IntegerField(blank=True, null=True)
    branch_id = models.IntegerField(blank=True, null=True)
    organization_id = models.IntegerField(blank=True, null=True)
    state = models.BooleanField(default=True)
    meta = models.JSONField(blank=True, null=True, default=dict)
    operator_signature = models.BooleanField(default=False, verbose_name="operator")
    moderator_signature = models.BooleanField(default=False, verbose_name="moderator")
    direktor_signature = models.BooleanField(default=False, verbose_name="direktor")
    loan_head_signature = models.BooleanField(default=False, verbose_name="kredit")
    monitoring_head_signature = models.BooleanField(default=False, verbose_name="monitoring")
    xlsx = models.FileField(blank=True, null=True, upload_to='uploads/xlsx_template/')

    def __str__(self):
        return f"Application {self.id} - {self.state}"

    def sum_signatures(self):
        percent = 0
        if self.moderator_signature:
            percent = percent + 25

templates/stepform/direktor_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2 class="mt-2">Direktor formasi</h2>
    <div class="alert alert-info" role="alert">
        "Roziman" belgilanganda keyin: <b>Shartnoma, Buyruq, Dalolatnoma, Grafik</b> fayllari PDF ko'rinishida shakllanadi!
    </div>

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">Hujjatlarni imzolash</div>
                <div class="card-body">

                    <form method="post" action=".">
                        {% csrf_token %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="direktor_signature"
                                   id="id_direktor_signature" required>
                            <label class="form-check-label" for="flexCheckDefault">
                                Roziman
                            </label>
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Yuborish</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/stepform/direktor_list.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filters %}
{% block content %}
    <h3 class="mt-2">Direktor sahifasi</h3>


    <div class="card mt-2">
        <div class="card-header">
            <i class="fas fa-table me-1"></i>
            Shartnomalar
        </div>
        <div class="card-body">
            <table id="applicationTable" class="display table table-bordered table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Shartnoma</th>
                    <th>Mijoz</th>
                    <th>Kredit</th>
                    <th>Garov</th>
                    <th>Progress</th>
                    <th>Imzolanish holati</th>
                    <th>Hujjatlar</th>
                </tr>
                </thead>

                <tbody>
                {% for obj in applications %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            <i class="fa-solid fa-file-lines"></i><span
                                class="fw-bold"> {{ obj.meta.contract.contract_number }}</span> <br>
                            <i class="fa-regular fa-calendar me-1"></i>{{ obj.meta.contract.contract_date }} yil <br>
                            {% if obj.meta.pledge.pledge_is_owner == 'yes' %}
                                <i class="fa-solid fa-file me-1"></i>STANDART
                            {% elif obj.meta.pledge.pledge_is_owner == 'no' %}
                                <i class="fa-solid fa-file me-1"></i>ISHONCHNOMA
                            {% endif %}
                        </td>
                        <td>
                            <i class="fa-solid fa-user me-1"></i> {{ obj.meta.customer.customer_fullname_initials }}
                            <br>
                            <i class="fa-solid fa-passport me-2"></i>{{ obj.meta.customer.customer_document }} <br>
                            <i class="fa-solid fa-address-book me-2"></i>{{ obj.meta.customer.customer_passport_pinfl }}
                            <br>
                            <i class="fa-solid fa-child-reaching me-2"></i>{{ obj.meta.customer.customer_birthDate }}
                            yil
                            <br>
                            <i class="fa-solid fa-phone me-1"></i>{{ obj.meta.customer.customer_phone1 }}
                        </td>
                        <td>
                            <i class="fa-solid fa-file-invoice-dollar me-1"></i>{{ obj.meta.contract.credit_loan_total }}
                            so'm <br>
                            <i class="fa-solid fa-file-code me-1"></i><span class="text text-uppercase"
                                                                            style="color: darkred">{{ obj.meta.contract.credit_type }}</span>
                        </td>

                        <td>
                            <i class="fa-solid fa-car me-1"></i>{{ obj.meta.pledge.pledge_modelName }} <br>
                            <i class="fa-solid fa-paint-roller me-1"></i>{{ obj.meta.pledge.pledge_vehicleColor }} <br>
                            <i class="fa-solid fa-car-on me-1"></i>{{ obj.meta.pledge.pledge_govNumber }}
                        </td>

                        <td>
                            <div class="progress">
                                <div class="progress-bar
                                    {% if obj.sum_signatures < 50 %}
                                        bg-danger
                                    {% elif obj.sum_signatures >= 50 and obj.sum_signatures < 75 %}
                                        bg-warning
                                    {% elif obj.sum_signatures > 75 %}
                                        bg-success
                                    {% endif %}
                                " role="progressbar"
                                     style="width: {{ obj.sum_signatures }}%;" aria-valuenow="{{ obj.sum_signatures }}"
                                     aria-valuemin="0" aria-valuemax="100">
                                    {{ obj.sum_signatures }}%
                                </div>
                            </div>
                        </td>
                        <td>
                            {% if obj.moderator_signature == False %}
                                <i class="fa-solid fa-file-signature me-1"></i>
                                <span class="text text-danger text-uppercase">Moderatorda</span> <br>
                            {% endif %}
                            {% if obj.loan_head_signature == False %}
                                <i class="fa-solid fa-file-signature me-1"></i>
                                <span class="text text-danger text-uppercase">Kreditlash bo’limida</span> <br>
                            {% endif %}
                            {% if obj.monitoring_head_signature == False %}
                                <i class="fa-solid fa-file-signature me-1"></i>
                                <span class="text text-danger text-uppercase">Monitoring bo’limida</span> <br>
                            {% endif %}
                            {% if obj.direktor_signature == False %}
                                <i class="fa-solid fa-file-signature me-1"></i>
                                <span class="text text-danger text-uppercase">Direktorda</span> <br>
                            {% endif %}

                            {% if obj.sum_signatures == 100 %}
                                <i class="fa-solid fa-file-circle-check"></i>
                                <span class="text text-danger text-success">IMZOLANGAN</span>
                            {% endif %}
                        </td>

                        <td>
                            {% if obj.direktor_signature == False and obj.sum_signatures >= 75 %}
                                <a href="{% url 'direktor_form' obj.pk %}" class="btn btn-outline-success btn-sm">IMZOLASH</a>
                            {% elif obj.sum_signatures == 100 %}
                                {% with doc=docs_dict|get_item:obj.id %}
                                {% if doc %}
                                        1. <a href="{{ doc.pdf_shartnoma.url }}" target="_blank">Shartnoma</a> <br>
                                        2. <a href="{{ doc.pdf_buyruq.url }}" target="_blank">Buyruq</a> <br>
                                        3. <a href="{{ doc.pdf_bayonnoma.url }}" target="_blank">Bayonnoma</a> <br>
                                        4. <a href="{{ doc.pdf_xulosa.url }}" target="_blank">Xulosa</a> <br>
                                        5. <a href="{{ doc.pdf_dalolatnoma.url }}" target="_blank">Dalolatnoma</a> <br>
                                        6. <a href="{{ doc.pdf_grafik.url }}" target="_blank">Grafik</a> <br>
                                        7. <a href="{{ doc.pdf_ariza.url }}" target="_blank">Ariza</a> <br>
                                        8. <a href="{{ doc.pdf_muqova.url }}" target="_blank">Muqova</a> <br>
                                        9. <a href="{{ doc.pdf_mijoz_anketasi.url }}" target="_blank">Mijoz anketasi</a>
                                        <br>
                                        10.
                                        <a href="{{ doc.pdf_majburiyatnoma.url }}" target="_blank">Majburiyatnoma</a>
                                        <br>
                                        11. <a href="{{ doc.pdf_kredit_ariza.url }}" target="_blank">Kredit ariza</a>
                                        <br>
                                        12. <a href="{{ doc.pdf_garov_ariza.url }}" target="_blank">Garov ariza</a> <br>
                                        13.<a href="{{ doc.pdf_akt_monitoring_1.url }}" target="_blank">AKT monitoring
                                        1</a> <br>
                                        14.<a href="{{ doc.pdf_akt_monitoring_2.url }}" target="_blank">AKT monitoring
                                        2</a> <br>
                                        15.<a href="{{ doc.pdf_akt_monitoring_3.url }}" target="_blank">AKT monitoring
                                        3</a> <br>
                                        16.<a href="{{ doc.pdf_akt_monitoring_4.url }}" target="_blank">AKT monitoring
                                        4</a> <br>
                                        17.<a href="{{ doc.pdf_notarius.url }}" target="_blank">Notariusga xat</a>
                                        <br>
                                {% endif %}
                                {% endwith %}
                            {% endif %}

                        </td>

                    </tr>
                {% endfor %}

                </tbody>
            </table>
            
            {% include 'includes/pagination.html' %}
        </div>
    </div>
{% endblock %}

{% block JavaScript %}
    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css"/>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#applicationTable').DataTable({
                pageLength: 10, // Har sahifada 10 ta yozuv
                language: {
                    "search": "Qidirish:",
                    "lengthMenu": "_MENU_ ta yozuvni ko‘rsatish",
                    "info": "Jami _TOTAL_ yozuvdan _START_ - _END_",
                    "paginate": {
                        "first": "Birinchi",
                        "last": "Oxirgi",
                        "next": "Keyingi",
                        "previous": "Oldingi"
                    },
                    "zeroRecords": "Hech narsa topilmadi",
                    "infoEmpty": "Yozuv yo‘q",
                    "infoFiltered": "(umumiy _MAX_ yozuvdan filtrlangan)"
                }
            });
        });
    </script>

{% endblock %}

templates/stepform/loan_head_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2 class="mt-2">Kreditlash bo’limi formasi</h2>
    <div class="alert alert-info" role="alert">
        "Roziman" belgilanganda keyin: <b>Shartnoma, Buyruq, Dalolatnoma, Grafik</b> fayllari PDF ko'rinishida shakllanadi!
    </div>

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">Hujjatlarni imzolash</div>
                <div class="card-body">

                    <form method="post" action=".">
                        {% csrf_token %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="loan_head_signature"
                                   id="id_loan_head_signature" required>
                            <label class="form-check-label" for="flexCheckDefault">
                                Roziman
                            </label>
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Yuborish</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/stepform/moderator_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2 class="mt-2">Moderator formasi</h2>
    <div class="alert alert-info col-6" role="alert">
        <span>Shartnoma ID: {{ obj }}</span> <br>
        <span>Shartnoma sanasi va raqami: {{ obj.meta.contract.contract_date }} yildagi {{ obj.meta.contract.contract_number }}-son</span> <br>
        <span>Mijoz: {{ obj.meta.customer.customer_fullname }}</span> <br>
        <span>Garov: {{ obj.meta.pledge.pledge_modelName }}, {{ obj.meta.pledge.pledge_govNumber }}</span> <br>
        <span>Garov summasi: {{ obj.meta.pledge.pledge_loan_total }} ({{ obj.meta.pledge.pledge_loan_total_word_uz }}) so'm</span> <br>
    </div>
    <div class="card col-6">
        <div class="card-header">Excel faylni yuklash va hujjatni imzolash</div>
        <div class="card-body">
            <form enctype="multipart/form-data" method="post" action=".">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_xlsx" class="form-label">Excel faylini yuklang</label>
                    <input class="form-control" type="file" name="xlsx" id="id_xlsx">
                </div>
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" name="moderator_signature"
                           id="id_moderator_signature" required>
                    <label class="form-check-label" for="flexCheckDefault">
                        Roziman
                    </label>
                </div>
                <!-- Yuborish tugmasi -->
                <button type="submit" class="btn btn-primary mt-2">Yuborish</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/stepform/monitoring_head_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h2 class="mt-2">Monitoring bo’limi formasi</h2>
    <div class="alert alert-info" role="alert">
        "Roziman" belgilanganda keyin: <b>Shartnoma, Buyruq, Dalolatnoma, Grafik</b> fayllari PDF ko'rinishida shakllanadi!
    </div>

    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">Hujjatlarni imzolash</div>
                <div class="card-body">

                    <form method="post" action=".">
                        {% csrf_token %}
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="monitoring_head_signature"
                                   id="id_monitoring_head_signature" required>
                            <label class="form-check-label" for="flexCheckDefault">
                                Roziman
                            </label>
                        </div>
                        <button type="submit" class="btn btn-primary mt-3">Yuborish</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/stepform/step_done.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="mt-4">Static Navigation</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">Static Navigation</li>
    </ol>

    <div class="alert alert-warning">STEP {{ step }}</div>
    <h1>Kiritildi</h1>

{% endblock %}

templates/stepform/step_form.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="mt-4">Static Navigation</h1>
    <ol class="breadcrumb mb-4">
        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
        <li class="breadcrumb-item active">Static Navigation</li>
    </ol>

    <div class="alert alert-warning">STEP FORM</div>
    <h1>{{ step }}</h1>



{% endblock %}